const fs = require('fs');
const path = require('path');

function processDirectory(dir) {
    const files = fs.readdirSync(dir);
    for (const file of files) {
        const fullPath = path.join(dir, file);
        if (fs.statSync(fullPath).isDirectory()) {
            processDirectory(fullPath);
        } else if (fullPath.endsWith('.tsx') || fullPath.endsWith('.css')) {
            let content = fs.readFileSync(fullPath, 'utf-8');

            if (fullPath.endsWith('.tsx')) {
                // Remove all dark: classes
                content = content.replace(/dark:[^\s"'\`]+/g, '');
                // Clean up any double spaces generated by the removal
                content = content.replace(/ \s+/g, ' ');
            }

            fs.writeFileSync(fullPath, content);
        }
    }
}

processDirectory(path.join(__dirname, 'src'));
console.log('Fixed styling in all src files.');
